# Generated by Django 3.2.25 on 2026-02-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlapp', '0003_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
