# Generated by Django 3.2.25 on 2026-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlapp', '0004_auto_20260209_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
