# Generated by Django 3.2.25 on 2026-06-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlapp', '0005_entry_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
